cookbook "apt", "=1.9.2"
cookbook "apache2", "=1.6.2"
cookbook "php", "=1.1.8"
cookbook "openssl", "=1.0.2"
cookbook "mysql", "=3.0.0"
cookbook "build-essential", "=1.3.4"
cookbook "xml", "=1.1.2"
cookbook "beachbum-bonfire", path: "../beachbum-bonfire"
